name: 'Release Build'

on:
  push:
    branches:
      - 'main'

env:
  CI: true

jobs:
  test:
    uses: the-camputer/react-conway/.github/workflows/unit_test.yml@main
  release:
    name: 'Build Release Artifact'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build Release
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build
